##########################################################
###################  测试环境的profile  ###################
##########################################################
spring:
  profiles: test
  datasource:
      url: jdbc:mysql://10.12.11.86:3306/giveu_secret?useUnicode=true&characterEncoding=UTF-8
      username: secret_rw
      password: rw_SECRET$092018
      filters: log4j,wall,mergeStat

logging:
  level: debug
  file: logs/guns.log
