##########################################################
##################  所有profile共有的配置  #################
##########################################################

###################  guns配置  ###################
guns:
  swagger-open: true #是否开启swagger (true/false)
  kaptcha-open: false #是否开启登录时验证码 (true/false)
  session-open: false #是否开启session验证 (true/false)
  #file-upload-path: d:/tmp  #文件上传目录(不配置的话为java.io.tmpdir目录)
  session-invalidate-time: 1800 #session失效时间 单位：秒
  session-validation-interval: 900 #多久检测一次失效的session 单位：秒

###################  项目启动端口  ###################
server:
  port: 8899

###################  beetl配置  ###################
beetl:
  delimiter-statement-start: \@   #开始结束标签(yaml不允许@开头)
  delimiter-statement-end: null
  resource-tagroot: common/tags   #自定义标签文件Root目录和后缀
  resource-tagsuffix: tag


###################  spring配置  ###################
spring:
  profiles:
    active: dev
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /WEB-INF/view
  http:
    converters:
      preferred-json-mapper: fastjson

###################  mybatis-plus配置  ###################
mybatis-plus:
  mapper-locations: classpath*:com/stylefeng/guns/**/mapping/*.xml,classpath*:mapper/*/*.xml
  typeAliasesPackage: com.stylefeng.guns.common.persistence.model,com.giveu.entity
  global-config:
    id-type: 1  #1:数据库ID自增   2:用户输入id   3:全局唯一id(IdWorker)   4:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用
#
#---
#
###########################################################
####################  开发环境的profile  ###################
###########################################################
#spring:
#  profiles: dev
#  datasource:
#      url: jdbc:mysql://10.12.11.185:3306/giveu_secret?useUnicode=true&characterEncoding=UTF-8
#      username: secret_rw
#      password: Rw_secret$201808
#      filters: log4j,wall,mergeStat
#
#logging:
#  level: debug
#  file: logs/guns.log
#
#---
#
###########################################################
####################  测试环境的profile  ###################
###########################################################
#spring:
#  profiles: test
#  datasource:
#      url: jdbc:mysql://10.12.11.86:3306/giveu_secret?useUnicode=true&characterEncoding=UTF-8
#      username: secret_rw
#      password: rw_SECRET$092018
#      filters: log4j,wall,mergeStat
#
#logging:
#  level: debug
#  file: logs/guns.log
#
#---
#
###########################################################
####################  正式环境的profile  ###################
###########################################################
#spring:
#  profiles: prd
#  datasource:
#      url: jdbc:mysql://127.0.0.1:3306/study?useUnicode=true&characterEncoding=UTF-8
#      username: root
#      password: root
#      filters: log4j,wall,mergeStat
#
#logging:
#  level: warn
#  file: logs/guns.log
#
