

##########################################################
###################  开发环境的profile  ###################
##########################################################
spring:
  profiles: dev
  datasource:
      url: jdbc:mysql://10.12.11.185:3306/giveu_secret?useUnicode=true&characterEncoding=UTF-8
      username: secret_rw
      password: Rw_secret$201808
      filters: log4j,wall,mergeStat

logging:
  level: debug
  file: logs/guns.log
